SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE enumeration;
TRUNCATE enumeration_item;
TRUNCATE private_message;
TRUNCATE contact;
TRUNCATE post;
TRUNCATE user_community;
TRUNCATE userprofile;
TRUNCATE users;
TRUNCATE community;
SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE community AUTO_INCREMENT = 1;
ALTER TABLE contact AUTO_INCREMENT = 1;
ALTER TABLE enumeration AUTO_INCREMENT = 1;
ALTER TABLE enumeration_item AUTO_INCREMENT = 1;
ALTER TABLE post AUTO_INCREMENT = 1;
ALTER TABLE private_message AUTO_INCREMENT = 1;
ALTER TABLE user_community AUTO_INCREMENT = 1;
ALTER TABLE userprofile AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

-- add status to enumeration
INSERT INTO enumeration (name) VALUES ('PENDING');
INSERT INTO enumeration (name) VALUES ('APPROVED');
INSERT INTO enumeration (name) VALUES ('REFUSED');
INSERT INTO enumeration (name) VALUES ('ADMIN');
INSERT INTO enumeration (name) VALUES ('PORTALADMIN');
INSERT INTO enumeration (name) VALUES ('USER');
INSERT INTO enumeration (name) VALUES ('LIKE');

-- create user profiles
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('54 Brown Place','Tacoma','Washington','innovate B2C functionalities','alexander.baar@edu.fh-joanneum.at','Alexander','Baar','253-883-9229','801-140-3618',null,98447,47,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('455 Carberry Street','New York City','New York','enhance frictionless e-services','sandjar.berdiev@edu.fh-joanneum.at','Sandjar','Berdiev','646-423-7060','505-219-4934',null,10170,66,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('4251 Fremont Point','Oklahoma City','Oklahoma','morph customized networks','reimer.bogdan@edu.fh-joanneum.at','Reimer','Bogdan','405-945-2897','650-287-1783',null,73190,404,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('96224 Esker Junction','Detroit','Michigan','generate dot-com communities','irfan.dogic@edu.fh-joanneum.at','Irfan','Dogic','313-360-4942','415-570-0683',null,48232,373,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('5756 Fairview Pass','Homestead','Florida','synergize dot-com e-commerce','florian.gumhold@edu.fh-joanneum.at','Florian','Gumhold','305-707-8564','304-844-6163',null,33034,942,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('24792 Upham Hill','Port Charlotte','Florida','reintermediate best-of-breed communities','bernhard.haring@edu.fh-joanneum.at','Bernhard','Haring','941-219-3640','251-975-5774',null,33954,702,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('6 Fremont Court','New York City','New York','transform user-centric portals','christian.hofer@edu.fh-joanneum.at','Christian','Hofer','212-362-5391','305-287-2449',null,10125,2,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('04168 Heffernan Lane','Athens','Georgia','recontextualize cutting-edge systems','robert.ionescu@edu.fh-joanneum.at','Robert','Ionescu','706-105-0028','210-821-1608',null,30605,57700,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('4968 Gale Plaza','Portland','Oregon','facilitate visionary applications','roitinger.michael@edu.fh-joanneum.at','Roitinger','Michael','971-101-9581','571-673-1192',null,97255,16510,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('277 Schiller Point','Springfield','Massachusetts','envisioneer B2C eyeballs','stefan.moder@edu.fh-joanneum.at','Stefan','Moder','413-258-7335','404-327-0613',null,1129,55,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('62 3rd Point','Springfield','Illinois','exploit e-business users','nevzad.mujic@edu.fh-joanneum.at','Nevzad','Mujic','217-473-3977','626-319-8097',null,62764,402,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('67342 Jenifer Junction','Saint Paul','Minnesota','grow customized e-services','matthias.pointinger@edu.fh-joannemu.at','Matthias','Pointinger','612-562-1953','260-478-7944',null,55108,85,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('40 Muir Place','Washington','District of Columbia','brand back-end initiatives','kerstin.rampler@edu.fh-joanneum.at','Kerstin','Rampler','202-932-5620','419-996-7799',null,20260,0,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('66 Union Avenue','Sacramento','California','empower granular deliverables','bjoern.sattler@edu.fh-joanneum.at','Björn','Sattler','916-564-0938','508-114-0343',null,94230,4,'Frontend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('30 Prairie Rose Terrace','Fresno','California','engineer web-enabled e-business','alexander.schug@edu.fh-joanneum.at','Alexander','Schug','559-424-6981','713-475-7731',null,93704,28102,'Backend');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('84 Johnson Crossing','New York City','New York','exploit dot-com infrastructures','josef.steppan@edu.fh-joanneum.at','Josef','Steppan','917-471-8907','312-103-7161',null,10034,684,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('08379 Lien Court','Mobile','Alabama','grow efficient markets','philipp.trummer@edu.fh-joanneum.at','Philipp ','Trummer','251-836-5478','571-407-2356',null,36616,4498,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('48260 Dapin Place','Round Rock','Texas','harness proactive supply-chains','philip.fuchsbichler@edu.fh-joanneum.at','Philip','Fuchsbichler','512-383-9062','218-153-0582',null,78682,9569,'Database');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('3201 Loeprich Circle','Trenton','New Jersey','empower open-source supply-chains','patrick.walter@edu.fh-joanneum.at','Patrick','Walter','609-503-9448','682-986-2500',null,8638,54,'');
insert into userprofile (address, city, country, description, email, firstname, lastname, mobile, phone, picture, plz, room, team) values ('01921 Maryland Avenue','Miami','Florida','leverage robust communities','christopher.wegl@edu.fh-joanneum.at','Christopher','Wegl','786-950-7917','916-825-0443',null,33124,56544,'Database');

-- create users
INSERT INTO users(username, password, fk_userprofile) VALUES ('baar','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',1);
INSERT INTO users(username, password, fk_userprofile) VALUES ('berdiev','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',2);
INSERT INTO users(username, password, fk_userprofile) VALUES ('bogdan','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',3);
INSERT INTO users(username, password, fk_userprofile) VALUES ('dogic','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',4);
INSERT INTO users(username, password, fk_userprofile) VALUES ('gumhold','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',5);
INSERT INTO users(username, password, fk_userprofile) VALUES ('haring','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',6);
INSERT INTO users(username, password, fk_userprofile) VALUES ('hofer','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',7);
INSERT INTO users(username, password, fk_userprofile) VALUES ('ionescu','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',8);
INSERT INTO users(username, password, fk_userprofile) VALUES ('michael','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',9);
INSERT INTO users(username, password, fk_userprofile) VALUES ('moder','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',10);
INSERT INTO users(username, password, fk_userprofile) VALUES ('mujic','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',11);
INSERT INTO users(username, password, fk_userprofile) VALUES ('pointinger','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',12);
INSERT INTO users(username, password, fk_userprofile) VALUES ('rampler','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',13);
INSERT INTO users(username, password, fk_userprofile) VALUES ('sattler','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',14);
INSERT INTO users(username, password, fk_userprofile) VALUES ('schug','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',15);
INSERT INTO users(username, password, fk_userprofile) VALUES ('steppan','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',16);
INSERT INTO users(username, password, fk_userprofile) VALUES ('trummer','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',17);
INSERT INTO users(username, password, fk_userprofile) VALUES ('fuchsbichler','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',18);
INSERT INTO users(username, password, fk_userprofile) VALUES ('walter','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',19);
INSERT INTO users(username, password, fk_userprofile) VALUES ('wegl','$2a$10$G32yZZc3cWXtscHt0VY/W.md1Nhnuf3PbPtUodqn0xooPZeuJBTYW',20);


-- add contacts
insert into contact (fk_contact_id, user_id) values (1,20);
insert into contact (fk_contact_id, user_id) values (2,19);
insert into contact (fk_contact_id, user_id) values (3,18);
insert into contact (fk_contact_id, user_id) values (4,17);
insert into contact (fk_contact_id, user_id) values (5,16);
insert into contact (fk_contact_id, user_id) values (6,15);
insert into contact (fk_contact_id, user_id) values (7,14);
insert into contact (fk_contact_id, user_id) values (8,13);
insert into contact (fk_contact_id, user_id) values (9,12);
insert into contact (fk_contact_id, user_id) values (10,11);
insert into contact (fk_contact_id, user_id) values (11,10);
insert into contact (fk_contact_id, user_id) values (12,9);
insert into contact (fk_contact_id, user_id) values (13,8);
insert into contact (fk_contact_id, user_id) values (14,7);
insert into contact (fk_contact_id, user_id) values (15,6);
insert into contact (fk_contact_id, user_id) values (16,5);
insert into contact (fk_contact_id, user_id) values (17,4);
insert into contact (fk_contact_id, user_id) values (18,3);
insert into contact (fk_contact_id, user_id) values (19,2);
insert into contact (fk_contact_id, user_id) values (20,1);
insert into contact (fk_contact_id, user_id) values (1,10);
insert into contact (fk_contact_id, user_id) values (2,9);
insert into contact (fk_contact_id, user_id) values (3,8);
insert into contact (fk_contact_id, user_id) values (4,7);
insert into contact (fk_contact_id, user_id) values (5,6);
insert into contact (fk_contact_id, user_id) values (6,5);
insert into contact (fk_contact_id, user_id) values (7,4);
insert into contact (fk_contact_id, user_id) values (8,3);
insert into contact (fk_contact_id, user_id) values (9,2);
insert into contact (fk_contact_id, user_id) values (10,1);
insert into contact (fk_contact_id, user_id) values (11,20);
insert into contact (fk_contact_id, user_id) values (12,19);
insert into contact (fk_contact_id, user_id) values (13,18);
insert into contact (fk_contact_id, user_id) values (14,17);
insert into contact (fk_contact_id, user_id) values (15,16);
insert into contact (fk_contact_id, user_id) values (16,15);
insert into contact (fk_contact_id, user_id) values (17,14);
insert into contact (fk_contact_id, user_id) values (18,13);
insert into contact (fk_contact_id, user_id) values (19,12);
insert into contact (fk_contact_id, user_id) values (20,11);
insert into contact (fk_contact_id, user_id) values (1,5);
insert into contact (fk_contact_id, user_id) values (2,4);
insert into contact (fk_contact_id, user_id) values (3,3);
insert into contact (fk_contact_id, user_id) values (4,2);
insert into contact (fk_contact_id, user_id) values (5,1);
insert into contact (fk_contact_id, user_id) values (6,10);
insert into contact (fk_contact_id, user_id) values (7,9);
insert into contact (fk_contact_id, user_id) values (8,8);
insert into contact (fk_contact_id, user_id) values (9,7);
insert into contact (fk_contact_id, user_id) values (10,6);
insert into contact (fk_contact_id, user_id) values (11,15);
insert into contact (fk_contact_id, user_id) values (12,14);
insert into contact (fk_contact_id, user_id) values (13,13);
insert into contact (fk_contact_id, user_id) values (14,12);
insert into contact (fk_contact_id, user_id) values (15,11);
insert into contact (fk_contact_id, user_id) values (16,20);
insert into contact (fk_contact_id, user_id) values (17,19);
insert into contact (fk_contact_id, user_id) values (18,18);
insert into contact (fk_contact_id, user_id) values (19,17);
insert into contact (fk_contact_id, user_id) values (20,16);


-- insert private messages

insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, 4);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 2, 5);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Integer ac neque.', 3, 6);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 4, 7);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 5, 8);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 6, 9);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Pellentesque viverra pede ac diam.', 7, 10);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Aenean lectus.', 8, 11);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Phasellus id sapien in sapien iaculis congue.', 9, 12);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Curabitur in libero ut massa volutpat convallis.', 10, 13);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 11, 14);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Mauris lacinia sapien quis libero.', 12, 15);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 13, 16);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Maecenas rhoncus aliquam lacus.', 14, 17);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nam tristique tortor eu pede.', 15, 18);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Maecenas rhoncus aliquam lacus.', 16, 19);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nullam porttitor lacus at turpis.', 17, 20);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 18, 1);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Fusce posuere felis sed lacus.', 19, 2);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 20, 3);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Vivamus tortor. Duis mattis egestas metus.', 1, 3);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Mauris lacinia sapien quis libero.', 2, 4);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nulla ac enim.', 3, 5);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Phasellus id sapien in sapien iaculis congue.', 4, 6);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Pellentesque ultrices mattis odio. Donec vitae nisi.', 5, 7);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 6, 8);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 7, 9);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nulla suscipit ligula in lacus.', 8, 10);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 9, 11);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('In congue.', 10, 12);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Morbi a ipsum.', 11, 13);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Proin risus. Praesent lectus.', 12, 14);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 13, 15);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 14, 16);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Curabitur in libero ut massa volutpat convallis.', 15, 17);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 16, 18);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 17, 19);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Maecenas rhoncus aliquam lacus.', 18, 20);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 19, 1);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nunc nisl.', 20, 2);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Phasellus sit amet erat. Nulla tempus.', 1, 2);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Etiam vel augue.', 2, 3);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Vivamus vel nulla eget eros elementum pellentesque.', 3, 4);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Aliquam non mauris.', 4, 5);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nunc purus.', 5, 6);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nulla ac enim.', 6, 7);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Aliquam erat volutpat.', 7, 8);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Cras in purus eu magna vulputate luctus.', 8, 9);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 9, 10);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 10, 11);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 11, 12);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 12, 13);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Nullam varius. Nulla facilisi.', 13, 14);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 14, 15);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Pellentesque at nulla.', 15, 16);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Vivamus tortor. Duis mattis egestas metus.', 16, 17);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 17, 18);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Aliquam erat volutpat. In congue.', 18, 19);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 19, 20);
insert into private_message (text, fk_user_id_receiver, fk_user_id_sender) values ('In hac habitasse platea dictumst.', 20, 1);

-- insert communities
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Bachelorarbeit 1 für SWD15.','Bachelorarbeit 1','Null',1,1);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Das Semester ist in 5 Einheiten aufgeteilt, wobei jede Einheit aus einer 3-stündigen Vorlesung und einem thematisch dazu passenden 3-stündigen Übungsblock besteht. Die Übungsblöcke folgen zeitnah (teilweise am selben Tag) der dazugehörigen Vorlesung.','Computer Vision','Null',1,2);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('In  the  course  ESP  students  improve  their  academic  writing  skills.','English for Scientific Purposes','Null',1,3);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Im Rahmen des Seminars Heterogene Systeme bauen die Studierenden eine vollständige, vernetzte, auf verschiedenen-unterschiedlichen (Betriebs-)Systemen basierende IT Infrastruktur auf. Dabei ist besonderer Wert auf Interoperabilität und (in Bezug auf die Benutzer) weitgehende Transparenz zu legen. Des Weiteren wird auf den Umgang mit Cross Platform Werkzeugen und Entwicklungsumgebungen fokusiert.','Heterogene Systeme','Null',1,4);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Mitarbeit -> Aktiv bei Lab, Etherpad, Zwischenabgaben, KEINE Klausur','Human Computer Interaction','Null',2,1);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Die Studierenden haben einen Überblick über möglich e Angriffsszenarien im IT-Umfeld und sind in der Lage Gegen/Abwehrmaßnahmen anzuwenden','IT-Security','Null',2,2);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Run a “real world” agile software delevopment project','Practical Software Engineering','Null',2,3);
insert into community (description, name, picture, enumeration_id, portaladmin_id) values ('Social Mining….','Social Web','Null',2,4);

-- insert posts
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-29 19:09:36', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 3, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-11-07 23:42:54', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, 18);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-15 21:48:12', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 1, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-19 00:33:15', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 2, 15);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-11-09 04:28:19', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 2, 16);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-08 13:49:00', 'Nunc purus.', 2, 7);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-04 18:23:05', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 2, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-21 15:25:56', 'Sed sagittis.', 2, 6);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-31 07:21:26', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-02 19:27:08', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, 1);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-16 14:30:53', 'Fusce posuere felis sed lacus.', 4, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-18 07:51:00', 'Sed vel enim sit amet nunc viverra dapibus.', 1, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-01 15:43:26', 'Morbi quis tortor id nulla ultrices aliquet.', 3, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-01 17:20:26', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 1, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-31 07:11:07', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-11 18:16:23', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 4, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-18 06:01:07', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 4, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-15 13:00:19', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-10 23:23:55', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 11);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-29 22:52:23', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 1, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-17 20:31:25', 'Proin eu mi.', 4, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-02 03:54:23', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-08 23:45:00', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 1, 16);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-15 22:19:44', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 2, 2);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-26 05:08:03', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 2, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-28 22:03:32', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-08 07:26:24', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1, 7);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-27 11:25:49', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 3, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-16 07:58:06', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 2, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-05 00:35:29', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 3, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-08 20:48:19', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-19 22:13:12', 'In quis justo.', 2, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-15 21:06:04', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 3, 16);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-08 23:25:44', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 2, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-30 00:44:15', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 4, 12);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-12 04:23:52', 'Aliquam non mauris.', 3, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-26 03:51:57', 'Morbi porttitor lorem id ligula.', 2, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-11-13 18:55:51', 'Donec dapibus.', 3, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-23 17:14:43', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 1, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-02 15:26:02', 'Aenean auctor gravida sem.', 3, 12);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-11 07:57:23', 'Nunc purus.', 3, 18);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-07 13:40:35', 'Praesent lectus.', 3, 5);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-17 02:22:17', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1, 13);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-12 23:20:30', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 4, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-12 06:51:44', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, 9);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-10 21:49:08', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 3, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-19 07:12:46', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 2, 7);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-13 19:57:51', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 2, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-30 02:41:14', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3, 9);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-16 16:15:34', 'Curabitur convallis.', 2, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-20 07:09:39', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 4, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-15 13:00:35', 'Donec quis orci eget orci vehicula condimentum.', 4, 12);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-14 05:42:05', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 4, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-17 10:41:56', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 4, 5);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-13 01:45:04', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 3, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-06 01:34:22', 'Duis aliquam convallis nunc.', 1, 9);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-11 22:15:43', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 4, 7);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-11-18 14:27:16', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-20 05:35:44', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 1, 7);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-22 14:50:10', 'Vivamus tortor. Duis mattis egestas metus.', 1, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-31 21:57:57', 'Aenean fermentum.', 1, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-02 18:11:20', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 4, 6);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-11-29 05:23:04', 'Pellentesque viverra pede ac diam.', 1, 1);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-15 19:11:17', 'In eleifend quam a odio.', 2, 5);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-29 02:59:03', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 3, 6);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-02 21:12:22', 'Morbi a ipsum. Integer a nibh.', 4, 12);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-05-16 10:59:58', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 1, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-24 12:01:14', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 6);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-05 10:58:06', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 3, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-07 18:31:51', 'Nulla facilisi.', 2, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-11-27 06:36:13', 'In quis justo. Maecenas rhoncus aliquam lacus.', 4, 8);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-30 16:36:56', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 4, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-20 09:22:36', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 2, 9);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-27 12:53:25', 'Fusce consequat.', 3, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-14 06:30:18', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 3, 13);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-06-17 02:35:28', 'In quis justo. Maecenas rhoncus aliquam lacus.', 1, 15);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-14 08:08:05', 'Vestibulum rutrum rutrum neque.', 4, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-04 22:14:48', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 2, 9);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-16 16:40:00', 'Nunc rhoncus dui vel sem. Sed sagittis.', 2, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-20 08:07:49', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 2, 13);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-15 01:00:06', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 2, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-17 13:21:46', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3, 4);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-03 11:43:02', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 1, 13);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-11-22 13:31:50', 'Donec quis orci eget orci vehicula condimentum.', 1, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-04-02 03:39:23', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 2, 14);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-23 01:05:50', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 1, 3);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-13 04:07:34', 'Etiam justo. Etiam pretium iaculis justo.', 2, 15);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-01-19 03:54:09', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, 18);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-12-31 17:39:55', 'Fusce consequat.', 1, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-07 03:57:32', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 4, 19);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-16 01:09:11', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 4, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-07-08 05:23:02', 'In blandit ultrices enim.', 2, 20);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-03-03 08:54:23', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 2, 5);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-10-30 19:59:31', 'Proin eu mi. Nulla ac enim.', 4, 2);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-07 09:27:03', 'Etiam faucibus cursus urna.', 1, 12);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-02-08 02:50:48', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 4, 10);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-09-12 09:03:50', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 3, 5);
insert into post (created, text, fk_community_id, fk_user_id) values ('2016-11-26 11:22:32', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 1, 17);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-19 12:17:02', 'Aenean auctor gravida sem.', 1, 6);
insert into post (created, text, fk_community_id, fk_user_id) values ('2017-08-24 08:07:58', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 1, 15);

-- insert childposts
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-23 17:57:27', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',1, 61, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-08 00:44:48', 'Pellentesque at nulla. Suspendisse potenti.',3, 55, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-18 05:25:26', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',4, 51, 13);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-09 00:51:00', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',1, 2, 5);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-09 04:59:41', 'Etiam justo.',1, 10, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-11-29 05:15:46', 'Proin risus.',4, 62, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-09 14:51:54', 'Morbi porttitor lorem id ligula.',4, 11, 5);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-15 21:45:12', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',4, 16, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-11 04:58:34', 'Etiam vel augue.',4, 19, 17);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-09 10:01:51', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',4, 16, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-17 11:56:10', 'In hac habitasse platea dictumst.',4, 62, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-29 05:26:57', 'Donec ut mauris eget massa tempor convallis.',2, 8, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-11-27 07:34:25', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',3, 28, 5);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-14 09:59:44', 'Nunc rhoncus dui vel sem.',3, 97, 12);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-09 06:45:42', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',4, 90, 2);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-01 17:56:23', 'Donec posuere metus vitae ipsum. Aliquam non mauris.',2, 73, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-05 10:25:03', 'Pellentesque eget nunc.',2, 50, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-10 03:18:59', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',2, 79, 17);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-05 05:23:27', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',3, 28, 12);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-09-09 15:00:35', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',4, 52, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-07 14:41:07', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',1, 86, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-01 12:31:26', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',1, 60, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-13 05:30:21', 'Vivamus in felis eu sapien cursus vestibulum.',1, 20, 11);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-18 13:20:31', 'Sed accumsan felis.',1, 27, 18);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-04 15:04:57', 'Pellentesque at nulla. Suspendisse potenti.',4, 57, 12);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-27 17:52:32', 'Integer tincidunt ante vel ipsum.',3, 30, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-14 12:32:34', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',4, 35, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-15 03:02:55', 'In hac habitasse platea dictumst.',1, 76, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-11-25 01:49:44', 'Phasellus in felis. Donec semper sapien a libero.',4, 11, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-09-30 19:44:00', 'Aliquam sit amet diam in magna bibendum imperdiet.',1, 61, 19);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-26 13:47:34', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',4, 96, 19);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-02 07:09:27', 'Sed ante.',2, 48, 9);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-16 05:41:47', 'Aliquam erat volutpat. In congue.',2, 50, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-09 01:24:14', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',1, 68, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-30 00:25:04', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.',1, 58, 1);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-02 16:13:49', 'In congue. Etiam justo. Etiam pretium iaculis justo.',4, 57, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-28 22:22:03', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',1, 88, 17);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-05 18:11:49', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.',3, 38, 4);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-22 00:13:07', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',1, 84, 11);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-22 21:34:33', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',1, 59, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-24 09:58:13', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',4, 90, 2);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-24 18:02:14', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',2, 6, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-17 19:23:41', 'In eleifend quam a odio.',1, 95, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-27 19:13:08', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',1, 43, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-17 07:12:43', 'Donec semper sapien a libero.',2, 29, 18);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-01 21:38:53', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',2, 92, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-25 22:02:52', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.',4, 44, 3);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-14 05:43:17', 'Vivamus tortor.',1, 12, 19);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-20 11:55:59', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.',3, 30, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-18 18:01:44', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',3, 65, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-10 12:29:25', 'Nulla nisl.',2, 81, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-03 16:32:02', 'Nulla tellus. In sagittis dui vel nisl.',1, 61, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-11-26 23:55:04', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',4, 96, 12);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-13 14:02:35', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.',3, 55, 13);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-09 13:32:48', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',1, 84, 3);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-18 21:39:44', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',1, 31, 11);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-11-23 04:53:33', 'Nulla ac enim.',4, 44, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-27 09:35:37', 'Nulla mollis molestie lorem. Quisque ut erat.',1, 58, 19);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-20 09:45:17', 'Ut at dolor quis odio consequat varius.',3, 1, 5);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-29 18:27:43', 'Aliquam erat volutpat. In congue.',4, 17, 8);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-25 03:08:56', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',4, 57, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-20 17:37:47', 'Morbi quis tortor id nulla ultrices aliquet.',1, 27, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-17 13:02:15', 'Vivamus tortor. Duis mattis egestas metus.',2, 81, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-01 06:52:28', 'Etiam pretium iaculis justo.',3, 97, 2);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-27 21:43:42', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',3, 13, 1);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-13 19:46:41', 'Sed ante.',1, 58, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-17 10:54:59', 'In sagittis dui vel nisl.',3, 1, 9);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-09-28 08:27:03', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',1, 9, 18);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-06 22:28:26', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',4, 19, 17);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-12 08:25:26', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',1, 68, 10);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-21 12:32:56', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',3, 40, 19);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-09-10 15:29:57', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.',3, 46, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-05 23:58:57', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',1, 45, 9);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-28 10:23:37', 'Suspendisse potenti.',1, 12, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-14 05:29:48', 'Curabitur in libero ut massa volutpat convallis.',3, 40, 17);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-18 04:56:19', 'Duis bibendum.',1, 14, 15);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-23 07:13:49', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',3, 38, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-28 06:45:41', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',3, 55, 2);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-06-25 00:57:10', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',3, 38, 7);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-21 15:47:18', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',2, 34, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-31 17:09:55', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',2, 50, 5);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-05 06:40:11', 'In hac habitasse platea dictumst.',1, 58, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-10 13:17:26', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',2, 70, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-10-26 19:04:24', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.',3, 69, 11);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-15 21:06:56', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',1, 39, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-20 11:29:43', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',4, 52, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-22 20:20:36', 'Suspendisse potenti.',1, 95, 2);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-03-26 09:56:15', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',2, 50, 7);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-05-20 17:05:59', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',1, 88, 18);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-17 05:23:37', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',4, 71, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-20 00:00:36', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',2, 50, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-15 16:26:49', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',1, 23, 14);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-11-12 12:07:43', 'Proin interdum mauris non ligula pellentesque ultrices.',2, 93, 1);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-29 22:27:22', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.',3, 36, 12);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-07-22 16:38:10', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',3, 13, 7);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-04-22 16:08:47', 'Aliquam non mauris.',4, 35, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-02-03 15:16:25', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',3, 69, 20);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2016-12-10 04:53:31', 'In eleifend quam a odio. In hac habitasse platea dictumst.',4, 44, 6);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-08-31 00:19:44', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',2, 64, 16);
insert into post (created, text, fk_community_id, parent_post_id, fk_user_id) values ('2017-01-12 20:15:52', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',3, 28, 1);


-- add some likes
insert into post_users (Post_id, likedByUsers_id) values (169, 9);
insert into post_users (Post_id, likedByUsers_id) values (113, 4);
insert into post_users (Post_id, likedByUsers_id) values (167, 10);
insert into post_users (Post_id, likedByUsers_id) values (147, 3);
insert into post_users (Post_id, likedByUsers_id) values (120, 10);
insert into post_users (Post_id, likedByUsers_id) values (157, 15);
insert into post_users (Post_id, likedByUsers_id) values (138, 3);
insert into post_users (Post_id, likedByUsers_id) values (29, 18);
insert into post_users (Post_id, likedByUsers_id) values (181, 9);
insert into post_users (Post_id, likedByUsers_id) values (69, 9);
insert into post_users (Post_id, likedByUsers_id) values (148, 20);
insert into post_users (Post_id, likedByUsers_id) values (187, 18);
insert into post_users (Post_id, likedByUsers_id) values (28, 18);
insert into post_users (Post_id, likedByUsers_id) values (27, 12);
insert into post_users (Post_id, likedByUsers_id) values (114, 2);
insert into post_users (Post_id, likedByUsers_id) values (176, 11);
insert into post_users (Post_id, likedByUsers_id) values (140, 18);
insert into post_users (Post_id, likedByUsers_id) values (52, 10);
insert into post_users (Post_id, likedByUsers_id) values (25, 7);
insert into post_users (Post_id, likedByUsers_id) values (98, 10);
insert into post_users (Post_id, likedByUsers_id) values (83, 17);
insert into post_users (Post_id, likedByUsers_id) values (183, 16);
insert into post_users (Post_id, likedByUsers_id) values (117, 12);
insert into post_users (Post_id, likedByUsers_id) values (1, 11);
insert into post_users (Post_id, likedByUsers_id) values (185, 5);
insert into post_users (Post_id, likedByUsers_id) values (104, 15);
insert into post_users (Post_id, likedByUsers_id) values (40, 4);
insert into post_users (Post_id, likedByUsers_id) values (198, 14);
insert into post_users (Post_id, likedByUsers_id) values (128, 14);
insert into post_users (Post_id, likedByUsers_id) values (65, 9);
insert into post_users (Post_id, likedByUsers_id) values (190, 19);
insert into post_users (Post_id, likedByUsers_id) values (191, 1);
insert into post_users (Post_id, likedByUsers_id) values (11, 16);
insert into post_users (Post_id, likedByUsers_id) values (78, 9);
insert into post_users (Post_id, likedByUsers_id) values (24, 9);
insert into post_users (Post_id, likedByUsers_id) values (103, 16);
insert into post_users (Post_id, likedByUsers_id) values (10, 6);
insert into post_users (Post_id, likedByUsers_id) values (198, 14);
insert into post_users (Post_id, likedByUsers_id) values (124, 6);
insert into post_users (Post_id, likedByUsers_id) values (58, 11);
insert into post_users (Post_id, likedByUsers_id) values (69, 11);
insert into post_users (Post_id, likedByUsers_id) values (109, 8);
insert into post_users (Post_id, likedByUsers_id) values (83, 19);
insert into post_users (Post_id, likedByUsers_id) values (198, 19);
insert into post_users (Post_id, likedByUsers_id) values (21, 4);
insert into post_users (Post_id, likedByUsers_id) values (199, 10);
insert into post_users (Post_id, likedByUsers_id) values (31, 12);
insert into post_users (Post_id, likedByUsers_id) values (27, 13);
insert into post_users (Post_id, likedByUsers_id) values (79, 4);
insert into post_users (Post_id, likedByUsers_id) values (165, 8);
insert into post_users (Post_id, likedByUsers_id) values (55, 16);
insert into post_users (Post_id, likedByUsers_id) values (29, 18);
insert into post_users (Post_id, likedByUsers_id) values (7, 18);
insert into post_users (Post_id, likedByUsers_id) values (160, 5);
insert into post_users (Post_id, likedByUsers_id) values (36, 9);
insert into post_users (Post_id, likedByUsers_id) values (136, 4);
insert into post_users (Post_id, likedByUsers_id) values (74, 15);
insert into post_users (Post_id, likedByUsers_id) values (41, 6);
insert into post_users (Post_id, likedByUsers_id) values (149, 10);
insert into post_users (Post_id, likedByUsers_id) values (172, 12);
insert into post_users (Post_id, likedByUsers_id) values (111, 17);
insert into post_users (Post_id, likedByUsers_id) values (4, 6);
insert into post_users (Post_id, likedByUsers_id) values (96, 6);
insert into post_users (Post_id, likedByUsers_id) values (119, 14);
insert into post_users (Post_id, likedByUsers_id) values (181, 2);
insert into post_users (Post_id, likedByUsers_id) values (7, 18);
insert into post_users (Post_id, likedByUsers_id) values (13, 12);
insert into post_users (Post_id, likedByUsers_id) values (40, 8);
insert into post_users (Post_id, likedByUsers_id) values (73, 3);
insert into post_users (Post_id, likedByUsers_id) values (133, 15);
insert into post_users (Post_id, likedByUsers_id) values (85, 19);
insert into post_users (Post_id, likedByUsers_id) values (130, 4);
insert into post_users (Post_id, likedByUsers_id) values (84, 19);
insert into post_users (Post_id, likedByUsers_id) values (58, 17);
insert into post_users (Post_id, likedByUsers_id) values (18, 7);
insert into post_users (Post_id, likedByUsers_id) values (147, 12);
insert into post_users (Post_id, likedByUsers_id) values (29, 15);
insert into post_users (Post_id, likedByUsers_id) values (3, 2);
insert into post_users (Post_id, likedByUsers_id) values (120, 14);
insert into post_users (Post_id, likedByUsers_id) values (125, 20);
insert into post_users (Post_id, likedByUsers_id) values (100, 18);
insert into post_users (Post_id, likedByUsers_id) values (48, 14);
insert into post_users (Post_id, likedByUsers_id) values (30, 12);
insert into post_users (Post_id, likedByUsers_id) values (198, 3);
insert into post_users (Post_id, likedByUsers_id) values (114, 15);
insert into post_users (Post_id, likedByUsers_id) values (118, 1);
insert into post_users (Post_id, likedByUsers_id) values (79, 7);
insert into post_users (Post_id, likedByUsers_id) values (108, 17);
insert into post_users (Post_id, likedByUsers_id) values (5, 2);
insert into post_users (Post_id, likedByUsers_id) values (144, 18);
insert into post_users (Post_id, likedByUsers_id) values (175, 7);
insert into post_users (Post_id, likedByUsers_id) values (7, 16);
insert into post_users (Post_id, likedByUsers_id) values (115, 16);
insert into post_users (Post_id, likedByUsers_id) values (91, 19);
insert into post_users (Post_id, likedByUsers_id) values (126, 2);
insert into post_users (Post_id, likedByUsers_id) values (95, 7);
insert into post_users (Post_id, likedByUsers_id) values (10, 15);
insert into post_users (Post_id, likedByUsers_id) values (106, 3);
insert into post_users (Post_id, likedByUsers_id) values (140, 20);
insert into post_users (Post_id, likedByUsers_id) values (91, 2);
insert into post_users (Post_id, likedByUsers_id) values (26, 19);
insert into post_users (Post_id, likedByUsers_id) values (14, 17);
insert into post_users (Post_id, likedByUsers_id) values (143, 20);
insert into post_users (Post_id, likedByUsers_id) values (132, 10);
insert into post_users (Post_id, likedByUsers_id) values (133, 15);
insert into post_users (Post_id, likedByUsers_id) values (188, 15);
insert into post_users (Post_id, likedByUsers_id) values (127, 18);
insert into post_users (Post_id, likedByUsers_id) values (174, 18);
insert into post_users (Post_id, likedByUsers_id) values (182, 10);
insert into post_users (Post_id, likedByUsers_id) values (177, 7);
insert into post_users (Post_id, likedByUsers_id) values (16, 10);
insert into post_users (Post_id, likedByUsers_id) values (139, 2);
insert into post_users (Post_id, likedByUsers_id) values (192, 8);
insert into post_users (Post_id, likedByUsers_id) values (66, 10);
insert into post_users (Post_id, likedByUsers_id) values (127, 7);
insert into post_users (Post_id, likedByUsers_id) values (77, 19);
insert into post_users (Post_id, likedByUsers_id) values (3, 8);
insert into post_users (Post_id, likedByUsers_id) values (87, 1);
insert into post_users (Post_id, likedByUsers_id) values (41, 15);
insert into post_users (Post_id, likedByUsers_id) values (29, 17);
insert into post_users (Post_id, likedByUsers_id) values (40, 17);
insert into post_users (Post_id, likedByUsers_id) values (109, 20);
insert into post_users (Post_id, likedByUsers_id) values (42, 20);
insert into post_users (Post_id, likedByUsers_id) values (74, 4);
insert into post_users (Post_id, likedByUsers_id) values (27, 8);
insert into post_users (Post_id, likedByUsers_id) values (65, 13);
insert into post_users (Post_id, likedByUsers_id) values (160, 3);
insert into post_users (Post_id, likedByUsers_id) values (127, 10);
insert into post_users (Post_id, likedByUsers_id) values (152, 19);
insert into post_users (Post_id, likedByUsers_id) values (63, 20);
insert into post_users (Post_id, likedByUsers_id) values (157, 13);
insert into post_users (Post_id, likedByUsers_id) values (155, 9);
insert into post_users (Post_id, likedByUsers_id) values (169, 8);
insert into post_users (Post_id, likedByUsers_id) values (163, 8);
insert into post_users (Post_id, likedByUsers_id) values (162, 19);
insert into post_users (Post_id, likedByUsers_id) values (6, 15);
insert into post_users (Post_id, likedByUsers_id) values (137, 19);
insert into post_users (Post_id, likedByUsers_id) values (176, 4);
insert into post_users (Post_id, likedByUsers_id) values (34, 5);
insert into post_users (Post_id, likedByUsers_id) values (181, 20);
insert into post_users (Post_id, likedByUsers_id) values (79, 16);
insert into post_users (Post_id, likedByUsers_id) values (147, 19);
insert into post_users (Post_id, likedByUsers_id) values (160, 11);
insert into post_users (Post_id, likedByUsers_id) values (21, 15);
insert into post_users (Post_id, likedByUsers_id) values (183, 19);
insert into post_users (Post_id, likedByUsers_id) values (110, 1);
insert into post_users (Post_id, likedByUsers_id) values (176, 12);
insert into post_users (Post_id, likedByUsers_id) values (37, 8);
insert into post_users (Post_id, likedByUsers_id) values (18, 18);
insert into post_users (Post_id, likedByUsers_id) values (39, 13);
insert into post_users (Post_id, likedByUsers_id) values (25, 19);
insert into post_users (Post_id, likedByUsers_id) values (107, 20);
insert into post_users (Post_id, likedByUsers_id) values (20, 6);
insert into post_users (Post_id, likedByUsers_id) values (154, 2);
insert into post_users (Post_id, likedByUsers_id) values (194, 19);
insert into post_users (Post_id, likedByUsers_id) values (6, 1);
insert into post_users (Post_id, likedByUsers_id) values (74, 13);
insert into post_users (Post_id, likedByUsers_id) values (90, 7);
insert into post_users (Post_id, likedByUsers_id) values (28, 14);
insert into post_users (Post_id, likedByUsers_id) values (179, 12);
insert into post_users (Post_id, likedByUsers_id) values (48, 15);
insert into post_users (Post_id, likedByUsers_id) values (165, 20);
insert into post_users (Post_id, likedByUsers_id) values (80, 2);
insert into post_users (Post_id, likedByUsers_id) values (131, 8);
insert into post_users (Post_id, likedByUsers_id) values (76, 9);
insert into post_users (Post_id, likedByUsers_id) values (39, 13);
insert into post_users (Post_id, likedByUsers_id) values (65, 8);
insert into post_users (Post_id, likedByUsers_id) values (195, 4);
insert into post_users (Post_id, likedByUsers_id) values (129, 1);
insert into post_users (Post_id, likedByUsers_id) values (149, 1);
insert into post_users (Post_id, likedByUsers_id) values (96, 8);
insert into post_users (Post_id, likedByUsers_id) values (14, 14);
insert into post_users (Post_id, likedByUsers_id) values (47, 7);
insert into post_users (Post_id, likedByUsers_id) values (74, 10);
insert into post_users (Post_id, likedByUsers_id) values (191, 7);
insert into post_users (Post_id, likedByUsers_id) values (15, 9);
insert into post_users (Post_id, likedByUsers_id) values (52, 5);
insert into post_users (Post_id, likedByUsers_id) values (83, 12);
insert into post_users (Post_id, likedByUsers_id) values (87, 1);
insert into post_users (Post_id, likedByUsers_id) values (41, 11);
insert into post_users (Post_id, likedByUsers_id) values (24, 15);
insert into post_users (Post_id, likedByUsers_id) values (159, 8);
insert into post_users (Post_id, likedByUsers_id) values (30, 13);
insert into post_users (Post_id, likedByUsers_id) values (154, 15);
insert into post_users (Post_id, likedByUsers_id) values (26, 8);
insert into post_users (Post_id, likedByUsers_id) values (119, 11);
insert into post_users (Post_id, likedByUsers_id) values (41, 10);
insert into post_users (Post_id, likedByUsers_id) values (38, 4);
insert into post_users (Post_id, likedByUsers_id) values (99, 2);
insert into post_users (Post_id, likedByUsers_id) values (200, 7);
insert into post_users (Post_id, likedByUsers_id) values (81, 7);
insert into post_users (Post_id, likedByUsers_id) values (145, 8);
insert into post_users (Post_id, likedByUsers_id) values (50, 10);
insert into post_users (Post_id, likedByUsers_id) values (35, 8);
insert into post_users (Post_id, likedByUsers_id) values (168, 2);
insert into post_users (Post_id, likedByUsers_id) values (103, 12);
insert into post_users (Post_id, likedByUsers_id) values (115, 16);
insert into post_users (Post_id, likedByUsers_id) values (114, 19);
insert into post_users (Post_id, likedByUsers_id) values (81, 18);
insert into post_users (Post_id, likedByUsers_id) values (127, 9);

-- admins
insert into enumeration_item (enumeration_id, users_id) values (4, 7);
insert into enumeration_item (enumeration_id, users_id) values (4, 12);
insert into enumeration_item (enumeration_id, users_id) values (4, 14);
insert into enumeration_item (enumeration_id, users_id) values (4, 4);
insert into enumeration_item (enumeration_id, users_id) values (4, 5);
insert into enumeration_item (enumeration_id, users_id) values (4, 6);
-- portaladmins
insert into enumeration_item (enumeration_id, users_id) values (5, 1);
insert into enumeration_item (enumeration_id, users_id) values (5, 8);
insert into enumeration_item (enumeration_id, users_id) values (5, 9);
insert into enumeration_item (enumeration_id, users_id) values (5, 10);
insert into enumeration_item (enumeration_id, users_id) values (5, 11);
insert into enumeration_item (enumeration_id, users_id) values (5, 2);
-- users
insert into enumeration_item (enumeration_id, users_id) values (6, 13);
insert into enumeration_item (enumeration_id, users_id) values (6, 3);
insert into enumeration_item (enumeration_id, users_id) values (6, 15);
insert into enumeration_item (enumeration_id, users_id) values (6, 16);
insert into enumeration_item (enumeration_id, users_id) values (6, 17);
insert into enumeration_item (enumeration_id, users_id) values (6, 18);
insert into enumeration_item (enumeration_id, users_id) values (6, 19);
insert into enumeration_item (enumeration_id, users_id) values (6, 20);

-- make users part of communities
insert into user_community (users_id, community_id) values (13, 1);
insert into user_community (users_id, community_id) values (1, 4);
insert into user_community (users_id, community_id) values (15, 4);
insert into user_community (users_id, community_id) values (11, 1);
insert into user_community (users_id, community_id) values (16, 3);
insert into user_community (users_id, community_id) values (16, 2);
insert into user_community (users_id, community_id) values (16, 4);
insert into user_community (users_id, community_id) values (8, 1);
insert into user_community (users_id, community_id) values (2, 2);
insert into user_community (users_id, community_id) values (9, 1);
insert into user_community (users_id, community_id) values (11, 4);
insert into user_community (users_id, community_id) values (5, 4);
insert into user_community (users_id, community_id) values (17, 3);
insert into user_community (users_id, community_id) values (8, 2);
insert into user_community (users_id, community_id) values (16, 3);
insert into user_community (users_id, community_id) values (2, 3);
insert into user_community (users_id, community_id) values (3, 4);
insert into user_community (users_id, community_id) values (16, 1);
insert into user_community (users_id, community_id) values (19, 3);
insert into user_community (users_id, community_id) values (16, 4);
insert into user_community (users_id, community_id) values (5, 1);
insert into user_community (users_id, community_id) values (15, 1);
insert into user_community (users_id, community_id) values (15, 4);
insert into user_community (users_id, community_id) values (4, 2);
insert into user_community (users_id, community_id) values (8, 3);
insert into user_community (users_id, community_id) values (15, 4);
insert into user_community (users_id, community_id) values (1, 2);
insert into user_community (users_id, community_id) values (5, 3);
insert into user_community (users_id, community_id) values (11, 3);
insert into user_community (users_id, community_id) values (15, 4);
insert into user_community (users_id, community_id) values (8, 4);
insert into user_community (users_id, community_id) values (13, 3);
insert into user_community (users_id, community_id) values (16, 1);
insert into user_community (users_id, community_id) values (16, 2);
insert into user_community (users_id, community_id) values (16, 4);
insert into user_community (users_id, community_id) values (11, 2);
insert into user_community (users_id, community_id) values (1, 1);
insert into user_community (users_id, community_id) values (10, 3);
insert into user_community (users_id, community_id) values (19, 1);
insert into user_community (users_id, community_id) values (17, 1);
insert into user_community (users_id, community_id) values (7, 1);
insert into user_community (users_id, community_id) values (7, 2);
insert into user_community (users_id, community_id) values (7, 3);
insert into user_community (users_id, community_id) values (7, 4);
